exports.apiEnum = {
  API_REGISTER: "/auth/register",
  API_LOGIN: "/auth/login",
  API_UPDATE_PROFILE: "/auth/update-detail",
  API_FORGOT_PASSWORD: "/auth/forget-password",
  API_RESET_PASSWORD: "/auth/reset-password/:resetToken",
  API_GET_TOKEN: "/auth/token",
  API_CHECK_STUDENT: "/check",
  API_UPDATE_PASSWORD: "/auth/update-password",
  API_GET_MY_PROFILE: "/auth/profile",
  API_CREATE_DOCUMENT: "/documents",
  API_GET_DOCUMENTS: "/documents",
  API_GET_DOCUMENT: "/documents/:documentId",
  API_DELETE_DOCUMENT: "/documents/:documentId",
  API_ACTIVE_DOCUMENT: "/documents/:documentId",
  API_CREATE_SKILL: "/auth/add-skill",
  API_DELETE_SKILL: "/auth/delete-skill",
  API_GET_SUBJECT: "/subjects",
  API_GET_SKILL: "/skills",
  API_GET_DOWNLOAD: "/download",
};
